#
# MMWCAS-RF-EVM configuration file
#
# Setup:
#   - Max Range: 9.26m
#   - Range resolution: ~5cm

[mimo]  # MIMO Configuration


[mimo.profile]
id = 0
startFrequency = 77                             # Start frequency in GHz
frequencySlope = 48.57                          # Chrip slope in MHz/us
idleTime = 7                                    # ADC idle time in us
adcStartTime = 6.4                              # ADC start time in us
rampEndTime = 69.07                             # Chrip ramp end time in us
txStartTime = 0                                 # TX start time in us
numAdcSamples = 185                             # Number of ADC samples per chrip
adcSamplingFrequency = 3000                     # ADC sampling frequency in ksps
rxGain = 48                                     # RX Gain in dB
hpfCornerFreq1 = 0                              # High Pass Filter 1 corner frequency | 0: 175 kHz, 1: 235 kHz, 2: 350 kHz, 3: 700 kHz
hpfCornerFreq2 = 0                              # High Pass Filter 2 corner frequency | 0: 350 kHz, 1: 700 kHz, 2: 1.4 MHz, 3: 2.8 MHz


[mimo.frame]
numFrames = 0                                   # Number of frames to record
numLoops = 16                                   # Number of chirp loops per frame
framePeriodicity = 100                          # Frame periodicity in ms


[mimo.channel]
rxChannelEn = 15                                # Enabled RX antenna bit field
txChannelEn = 7                                 # Enabled TX Antenna bit field
